version: '3.3'

services:
  web:
    build:
      context: ./front-end
      dockerfile: Dockerfile

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=development

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
      - back-end